<?php

namespace AppBundle\Repository;

/**
 * User1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User1Repository extends \Doctrine\ORM\EntityRepository
{
}
